### PR TITLE
use new branch for the product

### PR DESCRIPTION
**Pull request by fivejjs**
use the new branch to add crop mask

### CODE REVIEW

**Comment by pindge** [comment]
hmm, maybe I should ask how do we plan to use this for ows layer style development?

**Comment by fangfy** [comment]
For the description, we might not want to include all the details on features because they might change. I suggest the detailed model description or identifier goes into the json produced with the mask.
For the produce description: annual crop land map, produced from Sentinel-2 observations and ancillary information.

**Comment by fangfy** [comment]
> hmm, maybe I should ask how do we plan to use this for ows layer style development?

For the styling, we'll have a binary mask layer and an integer percent probability layer. We haven't designed how they should look like yet. Do we have something similar for Australia?

**Comment by pindge** [comment]
> For the styling, we'll have a binary mask layer and an integer percent probability layer. We haven't designed how they should look like yet. Do we have something similar for Australia?

@alexgleith , @whatnick I think only you two could answer this.

**Comment by alexgleith** [comment]
It's crops, so maybe it's green for crops, and transparent for non-crop?

Want me to pick a shade of green?

**Comment by whatnick** [comment]
Not relevant for the product, but relevant for OWS presentation.

**Review by fangfy — COMMENTED** [review]
I tried to update the description but doesn't seem to be getting the formatting right... @alexgleith hint?

**Review by fangfy — APPROVED** [review]

**Comment by fivejjs** [comment]
add crop mask eastern africa

**Pull request merged**
