### PR TITLE
Add Sentinel-1 from Sinergise draft product definition

### PR DESCRIPTION
**Pull request by alexgleith**
Tested and ready for review

### CODE REVIEW

**Review by fangfy — COMMENTED** [review]
Few points:
1. can we call it s1_nrb? it's probably level 2 but it's not same as s2 levels
2. linci is uint8 or int16? I think we said we can do uint8, will confirm it
3. mask description should be changed. I thought we only have 0 (no/invalid) and 1 (valid)?

**Review by fangfy — COMMENTED** [review]
Not critical, but do we need to call the file esa_s1_nrb.yaml? instead of just s1_rtc.yaml?

I really don't think we should set nodata 0 for mask. 0 is a valid mask value. If we want this to be integer, it should be 255 or something that's not in the mask?

Add alias "local_contributing_area" and "scattering_area" to area band?

**Comment by alexgleith** [comment]
In the WO product definition, we still say `1` is nodata, even though it's 'data' :-)

https://raw.githubusercontent.com/GeoscienceAustralia/digitalearthau/develop/digitalearthau/config/eo3/products-aws/ga_ls_wo_3.odc-product.yaml

**Comment by alexgleith** [comment]
Happy to change the name.

**Comment by fangfy** [comment]
I think this short description has everything covered: Sentinel-1 radiometric terrain corrected Gamma0 backscatter. (not sure if you need dash in gamma0)

**Pull request merged**
