### PR TITLE
Generate Terria catalogue from WMS layers

### PR DESCRIPTION
**Pull request by eefaye**
### Background
Current Terria catalogue (`/terria/africa-prod.json`) individually defines items by calling upon WMS layers.

Current catalogue structure almost exactly follows the WMS layer structure defined in the `root_cfg` files.
Instead of manually updating this whenever a new product is added or modified, the Terria catalogue can be automatically generated from the latest tagged version of the OWS.

Example of new catalogue format: Click on link and select "Explore map data"
https://maps.digitalearth.africa/#clean&share=s-akEUAXgb7Ux1vwj1INIQLmY1pkA 

Benefits include the folder and sublevel descriptions from the WMS layer files, which would otherwise have to be manually inputted and updated into the current Terria catalogue json.

### Proposed changes

Replace current Terria catalogue json which uses multiple nested `type: group` items with a single item which calls all WMS layers using `type:wms-group`

### Possible concerns
 - This creates an extra highest-level dropdown. This is not a problem as setting to `"isOpen": true` shows all headings automatically. Data61 have indicated removing this top-level folder may be part of a future code sprint
 - ~Currently verifying whether existing sharelinks will be broken~ Existing sharelinks will be broken. Currently confirming how editing the root config file affects sharelinks
 - ~Makes it difficult to exclude prod-listed WMS layers from the Terria catalogue. This is not a problem as they can be tested in `ows.dev` and `ows-latest` before being added to live production~ Items can be excluded from the catalogue using `"excludeMembers": ["layer name"]`

PR in draft form while I wait for response from Data61, please raise any additional concerns

### CODE REVIEW

**Comment by alexgleith** [comment]
This means that whatever we have in OWS will be in Terria.

Are we sure we want this?

**Comment by eefaye** [comment]
Yes. It does. From my understanding it only generates from the tagged versions though, so you would still be able to test in `dev` and `ows-latest`.
I'm also wondering if the `excludeMembers` line might let you exclude things? https://github.com/GeoscienceAustralia/dea-config/blob/master/dev/terria/terria-cube-v8.json#L1764

**Comment by eefaye** [comment]
Update - sharelinks seem robust to changes in root config structure, only affected by the `wms-group` name and the layer ID defined in the layer file. Currently being tested by Data61

> share data should continue to work regardless of any changes made to the intermediate level groups (even flattening the nested WMS group to a single-level group of all layers). As long as WMS layer names don't change and the id of the the "wms-group" entry in the catalogue is still reachable

Translation is **more comprehensive** when using the `wms-group` auto-gen catalogue as it translates headings as well. Text language is dependent on browser settings, not Terria interface selection

**Review by SpacemanPaul — APPROVED** [review]
Makes sense to me.

**Pull request merged**
