### PR TITLE
`mako_r` WOfS summary colourmaps

### PR DESCRIPTION
**Pull request by eefaye**
**In this PR**
 - Removed old WOfS dataset OWS configs, including for Landsat Collection 1 and Collection 2 Beta. *This means these services can no longer be accessed on Maps or by any OWS access mechanism, although the data may still be indexed on the ODC*
 - Reordered all files as one of the following:
   - `band.py` - dictionaries of bands used in layers 
   - `style.py` - colour ramps and styling, listed by layer. Legacy colourmaps have been separated into their own `style` file
   - `layer.py` - contains layer entities referred to in the `root_cfg` files. They import elements from `band` and `style` files. They contain the text shown in the Terria Catalogue
 - Styles only used in one product have been renamed to clearly denote applicable product (no suffix = WOFL, `summary_annual`, `summary_alltime`)
 - Styles have been renamed to clearly denote legacy colourmaps (prefix `legacy_`)
 - Currently no common styles across the two summary products
 
**Issues/Questions**
 - The WOFL layer in `ows_wofs_ls_cfg` defaults to native CRS `EPSG:3857` - do we want to change that to `EPSG:6933` to match the others?
 - Non-linear colour scaling in all summary product colourmaps (new and legacy) - *not perceptually uniform*
 - `Legacy` colourmaps - vmin for `annual` is 2% but 0.2% for `alltime` - why? 
 - `mako_r` colourmaps vmax set to 95% instead of `legacy` 100%

**For later**
- Clear observation count in both WOfS and GeoMAD also using odd colourmapping
- `viridis_r` colourmap trial

### CODE REVIEW

**Comment by eefaye** [comment]
@alexgleith DB checks are still failing. I would like to merge this to see how it looks on Maps dev/ows-latest, but as it is not ready for release it would be good if there are no planned tagged releases in the near future (couple of days)? Otherwise I can separate dev and ows-latest

**Comment by alexgleith** [comment]
This is not a DB check failing, it'll be a configuration issue. I'll review now.

**Comment by alexgleith** [comment]
This is the error @eefaye:

>ImportError: cannot import name 'legacy_style_wofs_summary_alltime_frequency_blue' from 'ows_refactored.wofs.style_wofs_ls_legacy' (/env/config/ows_refactored/wofs/style_wofs_ls_legacy.py)

Identified by running `docker-compose -f docker-compose.ows.yaml up` in the root of the `config` repo.

**Comment by eefaye** [comment]
@alexgleith `json.decoder.JSONDecodeError: Expecting value: line 204 column 13 (char 5206)`

**Comment by alexgleith** [comment]
Are you ok with this one? Basically inventory and config aren't matching... I would love to fix the tool so it highlighted the errors better!

**Comment by eefaye** [comment]
Where is `inventory` comparing `styles_list` to? I have matched `styles_list` with `styles` in the relevant `wofs/..._cfg.py` files. Is there somewhere else it is looking?
I expect prod to break as I want to troubleshoot dev first, but this is definitely dev right.

**Comment by eefaye** [comment]
@alexgleith we made it! Please feel free to squash as you see fit, I don't know how to do that

**Review by alexgleith — APPROVED** [review]

**Pull request merged**
