### PR TITLE
Update Sentinel-2 metadata and rename the file

### PR DESCRIPTION
**Pull request by alexgleith**
Changes:

- Added extra bands (AOT and WVP)
- Renamed bands to be the same as what comes from Element 84

Questions:

- Should the AOT and WVP be included in the product, or just added in the dataset (make them optional)?
- Should we make the product name different? (Currently it's `s2a_msil2a` and `s2b_msil2a`
- Should we name the file different?
- Are the band aliases and names ok?

### CODE REVIEW

**Comment by Kirill888** [comment]
I think in other products we prefer human readable names as a canonical name for a band, and original name `B01` goes into alias. This does mean that STAC -> yaml code will need to support band renaming. 

Difference between aliases and canonical name is that canonical name is used when loading data without asking for a set of specific bands.

**Comment by fangfy** [comment]
> I think in other products we prefer human readable names as a canonical name for a band, and original name `B01` goes into alias. This does mean that STAC -> yaml code will need to support band renaming.
> 
> Difference between aliases and canonical name is that canonical name is used when loading data without asking for a set of specific bands.

I actually think this is fine because the band names B01 - B12 are commonly used for S2 while human readable names are interpretive.

**Comment by alexgleith** [comment]
Is this QA band section going to work ok, @Kirill888?

```
- name: 'SCL'
  aliases: [mask, qa]
  units: '1'
  dtype: uint8
  nodata: 0
  flags_definition:
    qa:
      bits: [0,1,2,3,4,5,6,7]
      description: Sen2Cor Scene Classification
      values:
        1: saturated or defective
        2: dark area pixels
        3: cloud shadows
        4: vegetation
        5: bare soils
        6: water
        7: unclassified
        8: cloud medium probability
        9: cloud high probability
        10: thin cirrus
        11: snow or ice
```

**Comment by Kirill888** [comment]
@alexgleith it will work, it's just names for categories that are shared across products are different. There is value in using names as defined by provider's documentation though. We can always add another `flags_definition` item later on with "harmonized" names as used in `fmask`-based products: `shadow,water,snow`, doesn't really work for things like that since there are several cloud classifications.

**Pull request merged**
